# Generated by Django 4.1.5 on 2023-01-30 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('ClienteId', models.AutoField(primary_key=True, serialize=False)),
                ('Nome', models.CharField(max_length=100)),
                ('CPF', models.CharField(max_length=100, unique=True)),
                ('Telefone', models.CharField(max_length=100)),
                ('Sexo', models.CharField(max_length=100)),
                ('CEP', models.CharField(max_length=100)),
                ('Cidade', models.CharField(max_length=100)),
                ('Estado', models.CharField(max_length=100)),
                ('Logradouro', models.CharField(max_length=100)),
            ],
        ),
    ]
